"""Change User model

Revision ID: 9c8b3375885d
Revises: 60f329edd4ab
Create Date: 2024-06-22 10:20:46.106385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c8b3375885d'
down_revision: Union[str, None] = '60f329edd4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('image_count', sa.Integer(), server_default='0'))
    op.execute('UPDATE users SET is_active = true WHERE is_active IS NULL')
    op.execute('UPDATE users SET image_count = 0 WHERE image_count IS NULL')
    op.alter_column('users', 'is_active', nullable=False)
    op.alter_column('users', 'image_count', server_default=None, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_count')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
